###################################################################
# HCL Confidential
#
# OCO Source Materials
#
# Copyright HCL Technologies Limited 2016, 2019, 2020
#
# The source code for this program is not published or otherwise
# divested of its trade secrets, irrespective of what has been
# deposited with the U.S. Copyright Office.
###################################################################
{{- if .Values.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-7-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  chain-ca.pem: {{ .Values.elasticsearch7.esChainCa }}
  elasticsearch-admin.crt.pem: {{ .Values.elasticsearch7.esAdminCrt }}
  elasticsearch-admin.key: {{ .Values.elasticsearch7.esAdminKey }}
  elasticsearch-ca-password.txt: {{ .Values.elasticsearch7.esCAPassword }}
  elasticsearch-healthcheck.crt.pem: {{ .Values.elasticsearch7.esHealthcheckCrt }}
  elasticsearch-healthcheck.des3.key: {{ .Values.elasticsearch7.esHealthcheckDes3Key }}
  elasticsearch-healthcheck.key: {{ .Values.elasticsearch7.esHealthcheckKey }}
  elasticsearch-http.crt.pem: {{ .Values.elasticsearch7.esHttpCrt }}
  elasticsearch-http.key: {{ .Values.elasticsearch7.esHttpKey }}
  elasticsearch-key-password.txt: {{ .Values.elasticsearch7.esKeyPassword }}
  elasticsearch-metrics.crt.pem: {{ .Values.elasticsearch7.esMetricsCrt }}
  elasticsearch-metrics.key: {{ .Values.elasticsearch7.esMetricsKey }}
  elasticsearch-transport.crt.pem: {{ .Values.elasticsearch7.esTransportCrt }}
  elasticsearch-transport.key: {{ .Values.elasticsearch7.esTransportKey }}
  elasticsearch-peoplesearch.crt.pem: {{ .Values.elasticsearch7.esPeopleSearchCrt }}
  elasticsearch-peoplesearch.key: {{ .Values.elasticsearch7.esPeopleSearchKey }}
  elasticsearch-contentsearch.crt.pem: {{ .Values.elasticsearch7.esContentSearchCrt }}
  elasticsearch-contentsearch.key: {{ .Values.elasticsearch7.esContentSearchKey }}
  elasticsearch-metrics.p12: {{ .Values.elasticsearch7.esMetricsP12 }}
  elasticsearch-orientme.crt.pem: {{ .Values.elasticsearch7.esOrientmeCrt }}
  elasticsearch-orientme.key: {{ .Values.elasticsearch7.esOrientmeKey }}
  elasticsearch-orientme.p12: {{ .Values.elasticsearch7.esOrientmeP12 }}
{{- end }}
