#################################################################
#	HCL Confidential
#
#	OCO Source Materials
#
#	Copyright HCL Technologies Limited 2020
#
#	The source code for this program is not published or otherwise
#	divested of its trade secrets, irrespective of what has been
#	deposited with the U.S. Copyright Office.
###################################################################
{{- $refProject := .Values.project -}}
{{- $refImage := .Values.common.image -}}
{{- $refDeployment := .Values.client -}}
{{- $refProbe := .Values.common.probe -}}
{{- $refReplicaCount := .Values.replicaCount -}}
{{- $calMasterNumber := div $refReplicaCount 2 | add1 | quote -}}
{{- $calDefaultMasterNumber := div .Values.master.replicas 2 | add1 | quote }}
---
{{- if .Capabilities.APIVersions.Has "apps/v1" }}
apiVersion: apps/v1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: es-client-{{ .Values.elasticsearch.majorVersion }}
  labels:
    component: elasticsearch{{ .Values.elasticsearch.majorVersion }}
    role: client
spec:
  selector:
    matchLabels:
      component: elasticsearch{{ .Values.elasticsearch.majorVersion }}
      role: client
  {{ if $refReplicaCount | int | ne 0 }}replicas: {{ $refReplicaCount }}{{ else }}replicas: {{ $refDeployment.replicas }}{{ end }}
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
  template:
    metadata:
      labels:
        component: elasticsearch{{ .Values.elasticsearch.majorVersion }}
        role: client
    spec:
      serviceAccountName: elasticsearch{{ .Values.elasticsearch.majorVersion }}
      terminationGracePeriodSeconds: {{ .Values.common.terminationGracePeriodSeconds }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: "type"
                operator: In
                values: ["generic"]
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                 - key: "role"
                   operator: In
                   values: ["client"]
      initContainers:
{{- if .Values.common.allowPrivilegedContainers }}
  {{- if eq .Values.common.allowPrivilegedContainers true }}
      - name: sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144 "]
        securityContext:
          privileged: true
  {{- end }}
{{- end }}
      - name: init-chmod-data
        image: {{ .Values.image.repository }}/elasticsearch{{ .Values.elasticsearch.majorVersion }}:{{ .Values.image.tag }}
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        command:
          - sh
          - -c
          - |
            chown -R {{ .Values.common.esUserID }}:{{ .Values.common.esGroupID }} /data /backup
            chmod -R 0700 /data /backup
            ls -l /data /backup
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: storage
          mountPath: /data
        - name: backup
          mountPath: /backup
      - name: wait-master-provisioning
        image: {{ .Values.image.repository }}/elasticsearch{{ .Values.elasticsearch.majorVersion }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ $refImage.pullPolicy }}
        command: ['sh', '-c',
                  "status_text=$(/opt/elasticsearch-{{ .Values.elasticsearch.version }}/probe/master-readiness.sh); \
                   exit $?;" ]
        env:
        - name: KEY_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.common.secretKeyRefName }}
              key: elasticsearch-key-password.txt
        volumeMounts:
        - name: es-secrets-vol
          mountPath: /opt/elasticsearch-{{ .Values.elasticsearch.version }}/config/certs
          readOnly: true
      containers:
      - name: es-client
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        image: {{ .Values.image.repository }}/elasticsearch{{ .Values.elasticsearch.majorVersion }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ $refImage.pullPolicy }}
        resources:
          limits:
            cpu: {{ $refDeployment.resources.limits.cpu }}
            memory: {{ $refDeployment.resources.limits.mem }}
          requests:
            cpu: {{ $refDeployment.resources.requests.cpu }}
            memory: {{ $refDeployment.resources.requests.mem }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_NAME
          value: {{ .Values.common.env.CLUSTER_NAME }}
        - name: NUMBER_OF_MASTERS
          {{ if $refReplicaCount | int | ne 0 }}value: {{ $calMasterNumber }}{{ else }}value: {{ $calDefaultMasterNumber }}{{ end }}
        - name: MEMORY_LOCK
          value: {{ .Values.common.env.MEMORY_LOCK | quote }}
        - name: NODE_MASTER
          value: "false"
        - name: NODE_DATA
          value: "false"
        - name: APP_NAME
          value: "ElasticsearchClient"
        {{ if .Values.common.networkHost }}
        - name: "NETWORK_HOST"
          value: {{ .Values.common.networkHost }}
        {{ end }}
        - name: HTTP_ENABLE
          value: "true"
        - name: "ES_JAVA_OPTS"
          value: "{{ .Values.client.ES_JAVA_OPTS_XMS }} {{ .Values.client.ES_JAVA_OPTS_XMX }}"
        - name: KEY_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.common.secretKeyRefName }}
              key: elasticsearch-key-password.txt
        {{- if eq .Values.elasticsearch5.migrate true }}
        - name: ELASTICSEARCH5_HOST
          value: {{ .Values.elasticsearch5.host }}
        - name: ELASTICSEARCH5_PORT
          value: {{ .Values.elasticsearch5.port | quote}}
        {{- end }}
        - name: ELASTICSEARCH5_MIGRATE
          value: {{ .Values.elasticsearch5.migrate | quote}}
        ports:
        - containerPort: {{ $refProject.containerPortHttp }}
          name: http
          protocol: TCP
        - containerPort: {{ $refProject.containerPortTCP }}
          name: transport
          protocol: TCP
        volumeMounts:
        - name: storage
          mountPath: /data
        - name: backup
          mountPath: /backup
        - name: es-secrets-vol
          mountPath: /opt/elasticsearch-{{ .Values.elasticsearch.version }}/config/certs
          readOnly: true
  {{- if eq .Values.elasticsearch5.migrate true }}
        - name: es-5-secrets-vol
          mountPath: /opt/elasticsearch-{{ .Values.elasticsearch.version }}/config/es5certs
          readOnly: true
  {{- end }}
        readinessProbe:
          #tcpSocket:
          #  port: transport
          initialDelaySeconds: {{ $refProbe.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ $refProbe.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ $refProbe.readinessProbe.timeoutSeconds }}
          exec:
            command:
              - sh
              - -c
              - |
                #!/usr/bin/env bash -e
                # If the node is starting up wait for the cluster to be green
                # Once it has started only check that the node itself is responding
                sendRequest="/opt/elasticsearch-${ES_VERSION}/probe/sendRequest.sh"
                health_status=$(${sendRequest} --to-master GET /_cluster/health?wait_for_status=green&timeout=1s)
                cluster_status=$(echo $health_status|sed "s/,/\n/g"|grep status|sed -e "s/\"status\"//g" -e "s/\://g" -e "s/\"//g")
                echo ${cluster_status}
                set +f
                # if return text contains green or yellow, then Cluster is Healthy.
                if [[ ${cluster_status} == "green" ]] || [[ ${cluster_status} == "yellow" ]]; then
                  echo "Cluster is Healthly with status: ${cluster_status}"
                  exit 0
                else
                  echo "elasticsearch client failed to achieve ready state - Cluster is UNHealthly with status: ${cluster_status}"
                  exit 1
                fi
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: {{ $refProbe.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ $refProbe.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ $refProbe.livenessProbe.timeoutSeconds }}
      volumes:
        - name: "storage"
          emptyDir: {}
        - name: backup
          {{- if (and (eq .Values.deploymentType "cloud") (not (empty .Values.deploymentType))) }}
          emptyDir: {}
          {{- else }}
          persistentVolumeClaim:
            claimName: es-pvc-backup-7
          {{- end }}
        - name: es-secrets-vol
          secret:
            secretName: {{ .Values.common.secretKeyRefName }}
  {{- if eq .Values.elasticsearch5.migrate true }}
        - name: es-5-secrets-vol
          secret:
            secretName: {{ .Values.common.es5secretKeyRefName }}
  {{- end }}
      imagePullSecrets:
        - name: {{ .Values.common.imagePullSecrets.name }}
